# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_auto_20170220_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mailing_list',
        ),
        migrations.AlterField(
            model_name='person',
            name='service_subscription',
            field=models.CharField(choices=[('all', 'All Services'), ('mug', 'MUG'), ('vittles', 'Vital Vittles'), ('snaxa', 'Hoya Snaxa'), ('ug', 'Uncommon Grounds'), ('midnight', 'Midnight Mug'), ('hilltoss', 'Hilltoss')], default='all', max_length=256),
        ),
    ]
