# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_auto_20170220_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('all', 'All Services'), ('mug', 'MUG'), ('vittles', 'Vital Vittles'), ('snaxa', 'Hoya Snaxa'), ('ug', 'Uncommon Grounds'), ('midnight', 'Midnight Mug'), ('hilltoss', 'Hilltoss')], default='all', max_length=256)),
                ('discount', models.CharField(choices=[('all', 'All Discounts'), ('$1.50 Off', '$1.50 Off'), ('1.50 Off', '1.50 Off'), ('CREDITED Spoilage', 'CREDITED Spoilage'), ('Cup Reuse', 'Cup Reuse'), ('Espresso 10 Drinks Card', 'Espresso 10 Drinks Card'), ('Espresso Loyalty Card', 'Espresso Loyalty Card'), ('Expired', 'Expired'), ('Green Bag Discount', 'Green Bag Discount'), ('Lau Employee Appreciation', 'Lau Employee Appreciation'), ('Office Hours', 'Office Hours'), ('Shift Drink - Accounting', 'Shift Drink - Accounting'), ('Shift Drink - Catering', 'Shift Drink - Catering'), ('Shift Drink - Hilltoss', 'Shift Drink - Hilltoss'), ('Shift Drink - Hoya Snaxa', 'Shift Drink - Hoya Snaxa'), ('Shift Drink - ITM', 'Shift Drink - ITM'), ('Shift Drink - IT+M', 'Shift Drink - IT+M'), ('Shift Drink - Main Office', 'Shift Drink - Main Office'), ('Shift Drink - Midnight', 'Shift Drink - Midnight'), ('Shift Drink - MUG', 'Shift Drink - MUG'), ('Shift Drink - Seasonal', 'Shift Drink - Seasonal'), ('Shift Drink - UG', 'Shift Drink - UG'), ('Shift Drink - Vital Vittles', 'Shift Drink - Vital Vittles'), ('Sorry Card', 'Sorry Card'), ('Spoil', 'Spoil'), ('Use - Accounting', 'Use - Accounting'), ('Use - Catering', 'Use - Catering'), ('Use - Hilltoss', 'Use - Hilltoss'), ('Use - Hoya Snaxa', 'Use - Hoya Snaxa'), ('Use - ITM', 'Use - ITM'), ('Use - Main Office', 'Use - Main Office'), ('Use - Midnight', 'Use - Midnight'), ('Use - MUG', 'Use - MUG'), ('Use - Storage', 'Use - Storage'), ('Use - UG', 'Use - UG'), ('Use - Vittles', 'Use - Vittles')], default='all', max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='discount_subscription',
        ),
        migrations.RemoveField(
            model_name='person',
            name='service_subscription',
        ),
        migrations.AddField(
            model_name='person',
            name='subscriptions',
            field=models.ManyToManyField(to='mailer.Subscription'),
        ),
    ]
