# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_auto_20170220_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='service',
        ),
        migrations.DeleteModel(
            name='MailingList',
        ),
    ]
