# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpoilageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpoilageReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Service')),
            ],
        ),
        migrations.AddField(
            model_name='spoilageitem',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoilage_report.SpoilageReport'),
        ),
    ]
