# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoilage_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoilageitem',
            name='variant',
            field=models.CharField(default='', max_length=100),
        ),
    ]
