# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoilage_report', '0003_auto_20151227_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoilageitem',
            name='transaction_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
