# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 06:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoilage_report', '0004_spoilageitem_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoilageitem',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 5, 6, 24, 35, 940236)),
        ),
    ]
