# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spoilage_report', '0005_spoilageitem_transaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spoilageitem',
            name='transaction_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
